"""Browser theme generators - Firefox, Zen, Chrome."""

import json
from pathlib import Path
from theme_maker.palette import hex_to_rgb


def _accent_rgba(p: dict) -> str:
    r, g, b = hex_to_rgb(p["accent"])
    return f"rgba({r}, {g}, {b}"


def generate_firefox_userchrome(p: dict, name: str) -> str:
    return f"""/* {name} Theme - Firefox userChrome.css
 * Auto-generated by Theme Maker
 *
 * IMPORTANT: Enable in about:config:
 * toolkit.legacyUserProfileCustomizations.stylesheets = true
 */

:root {{
  --sw-bg-deepest: {p["bg_deepest"]};
  --sw-bg-main: {p["bg_main"]};
  --sw-bg-surface: {p["bg_surface"]};
  --sw-bg-elevated: {p["bg_elevated"]};
  --sw-border: {p["border"]};
  --sw-accent: {p["accent"]};
  --sw-accent-hover: {p["accent_hover"]};
  --sw-accent-light: {p["accent_light"]};
  --sw-text: {p["text"]};
  --sw-text-muted: {p["text_muted"]};
  --sw-glow: {_accent_rgba(p)}, 0.15);
  --sw-glow-strong: {_accent_rgba(p)}, 0.3);

  --toolbar-bgcolor: var(--sw-bg-main) !important;
  --toolbar-color: var(--sw-text) !important;
  --toolbar-field-background-color: var(--sw-bg-deepest) !important;
  --toolbar-field-color: var(--sw-text) !important;
  --toolbar-field-border-color: var(--sw-border) !important;
  --toolbar-field-focus-background-color: var(--sw-bg-deepest) !important;
  --toolbar-field-focus-border-color: var(--sw-accent) !important;
  --urlbar-box-bgcolor: var(--sw-bg-deepest) !important;
  --urlbar-box-focus-bgcolor: var(--sw-bg-deepest) !important;
  --urlbar-box-hover-bgcolor: var(--sw-bg-elevated) !important;
  --urlbar-box-text-color: var(--sw-text) !important;
  --lwt-toolbar-field-highlight: var(--sw-accent) !important;
  --lwt-toolbar-field-highlight-text: #ffffff !important;
  --autocomplete-popup-background: var(--sw-bg-surface) !important;
  --autocomplete-popup-color: var(--sw-text) !important;
  --autocomplete-popup-highlight-background: var(--sw-glow-strong) !important;
  --autocomplete-popup-highlight-color: var(--sw-text) !important;
  --tab-selected-bgcolor: var(--sw-bg-main) !important;
  --tab-selected-textcolor: var(--sw-text) !important;
  --lwt-accent-color: var(--sw-bg-deepest) !important;
  --lwt-text-color: var(--sw-text) !important;
  --arrowpanel-background: var(--sw-bg-surface) !important;
  --arrowpanel-color: var(--sw-text) !important;
  --arrowpanel-border-color: var(--sw-border) !important;
  --panel-separator-color: var(--sw-border) !important;
  --focus-outline-color: var(--sw-accent) !important;
}}

#main-window, #navigator-toolbox {{
  background-color: var(--sw-bg-deepest) !important;
}}

#TabsToolbar {{
  background-color: var(--sw-bg-deepest) !important;
  border-bottom: 1px solid var(--sw-border) !important;
}}

.tabbrowser-tab {{
  background-color: transparent !important;
  color: var(--sw-text-muted) !important;
  border-radius: 8px 8px 0 0 !important;
  margin-top: 3px !important;
}}

.tabbrowser-tab .tab-background {{
  border-radius: 8px 8px 0 0 !important;
  background: transparent !important;
  border: none !important;
}}

.tabbrowser-tab[selected="true"] {{
  color: var(--sw-text) !important;
}}

.tabbrowser-tab[selected="true"] .tab-background {{
  background: var(--sw-bg-main) !important;
}}

.tabbrowser-tab:hover:not([selected="true"]) .tab-background {{
  background: var(--sw-glow) !important;
}}

.tab-line {{
  background-color: var(--sw-accent) !important;
  height: 2px !important;
}}

.tabbrowser-tab:not([selected="true"]) .tab-line {{
  background-color: transparent !important;
}}

.tab-close-button {{
  fill: var(--sw-text-muted) !important;
  border-radius: 50% !important;
}}

.tab-close-button:hover {{
  background-color: var(--sw-accent) !important;
  fill: white !important;
}}

#new-tab-button, #tabs-newtab-button {{
  fill: var(--sw-text) !important;
  border-radius: 8px !important;
}}

#new-tab-button:hover, #tabs-newtab-button:hover {{
  background-color: var(--sw-glow) !important;
}}

#alltabs-button {{
  fill: var(--sw-text) !important;
}}

#nav-bar {{
  background-color: var(--sw-bg-main) !important;
  border-bottom: 1px solid var(--sw-border) !important;
  padding: 2px 4px !important;
}}

#urlbar-background {{
  background-color: var(--sw-bg-deepest) !important;
  border: 1px solid var(--sw-border) !important;
  border-radius: 10px !important;
}}

#urlbar[focused="true"] > #urlbar-background {{
  border-color: var(--sw-accent) !important;
  box-shadow: 0 0 0 3px {_accent_rgba(p)}, 0.2) !important;
}}

#urlbar-input {{
  color: var(--sw-text) !important;
}}

#urlbar-input::placeholder {{
  color: var(--sw-text-muted) !important;
}}

.urlbarView {{
  background: var(--sw-bg-surface) !important;
  border-radius: 0 0 12px 12px !important;
}}

.urlbarView-row {{
  border-radius: 8px !important;
  padding: 4px 8px !important;
}}

.urlbarView-row:hover, .urlbarView-row[selected] {{
  background: var(--sw-glow) !important;
}}

#searchbar {{
  background-color: var(--sw-bg-deepest) !important;
  border: 1px solid var(--sw-border) !important;
  border-radius: 10px !important;
}}

#nav-bar toolbarbutton, #TabsToolbar toolbarbutton {{
  fill: var(--sw-text) !important;
  color: var(--sw-text) !important;
  border-radius: 8px !important;
}}

#nav-bar toolbarbutton:hover, #TabsToolbar toolbarbutton:hover {{
  background-color: var(--sw-glow) !important;
}}

#nav-bar toolbarbutton[checked="true"], #nav-bar toolbarbutton:active {{
  background-color: var(--sw-glow-strong) !important;
}}

#back-button, #forward-button {{
  fill: var(--sw-text) !important;
  border-radius: 50% !important;
}}

#back-button:hover, #forward-button:hover {{
  background-color: var(--sw-glow) !important;
}}

#PersonalToolbar {{
  background-color: var(--sw-bg-deepest) !important;
  border-bottom: 1px solid var(--sw-border) !important;
  padding: 2px 4px !important;
}}

#PlacesToolbarItems toolbarbutton {{
  color: var(--sw-text-muted) !important;
  border-radius: 6px !important;
}}

#PlacesToolbarItems toolbarbutton:hover {{
  background-color: var(--sw-glow) !important;
  color: var(--sw-text) !important;
}}

menupopup {{
  background-color: var(--sw-bg-surface) !important;
  color: var(--sw-text) !important;
  border: 1px solid var(--sw-border) !important;
  border-radius: 12px !important;
  padding: 4px !important;
}}

menuitem {{
  color: var(--sw-text) !important;
  border-radius: 8px !important;
  padding: 6px 10px !important;
}}

menuitem:hover, menuitem[_moz-menuactive="true"] {{
  background-color: var(--sw-glow) !important;
}}

menuseparator {{
  border-color: var(--sw-border) !important;
}}

#contentAreaContextMenu {{
  background-color: var(--sw-bg-surface) !important;
  color: var(--sw-text) !important;
  border: 1px solid var(--sw-border) !important;
  border-radius: 12px !important;
}}

#sidebar-box {{
  background-color: var(--sw-bg-deepest) !important;
  border-right: 1px solid var(--sw-border) !important;
}}

#sidebar-header {{
  background-color: var(--sw-bg-surface) !important;
  border-bottom: 1px solid var(--sw-border) !important;
  color: var(--sw-text) !important;
}}

findbar {{
  background-color: var(--sw-bg-surface) !important;
  color: var(--sw-text) !important;
  border-top: 1px solid var(--sw-border) !important;
}}

findbar textbox {{
  background-color: var(--sw-bg-deepest) !important;
  color: var(--sw-text) !important;
  border: 1px solid var(--sw-border) !important;
  border-radius: 8px !important;
}}

findbar textbox:focus {{
  border-color: var(--sw-accent) !important;
  box-shadow: 0 0 0 2px {_accent_rgba(p)}, 0.2) !important;
}}

#downloadsPanel {{
  background-color: var(--sw-bg-surface) !important;
}}

.webextension-popup-browser {{
  background-color: var(--sw-bg-main) !important;
}}

scrollbar {{
  background-color: transparent !important;
}}

scrollbar thumb {{
  background-color: {_accent_rgba(p)}, 0.4) !important;
  border-radius: 100px !important;
}}

scrollbar thumb:hover {{
  background-color: {_accent_rgba(p)}, 0.6) !important;
}}

::selection {{
  background-color: {_accent_rgba(p)}, 0.4) !important;
  color: var(--sw-text) !important;
}}

#private-browsing-indicator-with-label {{
  background-color: var(--sw-accent) !important;
  color: white !important;
  border-radius: 6px !important;
}}

#statuspanel #statuspanel-label {{
  background: var(--sw-bg-surface) !important;
  border: 1px solid var(--sw-border) !important;
  border-radius: 6px !important;
  color: var(--sw-text-muted) !important;
}}
"""


def generate_firefox_usercontent(p: dict, name: str) -> str:
    return f"""/* {name} Theme - Firefox userContent.css
 * Auto-generated by Theme Maker
 */

:root {{
  --sw-bg-deepest: {p["bg_deepest"]};
  --sw-bg-main: {p["bg_main"]};
  --sw-bg-surface: {p["bg_surface"]};
  --sw-bg-elevated: {p["bg_elevated"]};
  --sw-border: {p["border"]};
  --sw-accent: {p["accent"]};
  --sw-accent-hover: {p["accent_hover"]};
  --sw-text: {p["text"]};
  --sw-text-muted: {p["text_muted"]};
  --sw-glow: {_accent_rgba(p)}, 0.15);
}}

@-moz-document url("about:newtab"), url("about:home") {{
  body {{
    background-color: var(--sw-bg-deepest) !important;
    color: var(--sw-text) !important;
  }}

  .search-wrapper .search-handoff-button {{
    background-color: var(--sw-bg-surface) !important;
    border: 1px solid var(--sw-border) !important;
    border-radius: 12px !important;
  }}

  .search-wrapper .search-handoff-button:hover {{
    border-color: {_accent_rgba(p)}, 0.4) !important;
  }}

  .search-wrapper input {{
    background-color: var(--sw-bg-surface) !important;
    border: 1px solid var(--sw-border) !important;
    border-radius: 12px !important;
    color: var(--sw-text) !important;
  }}

  .search-wrapper input:focus {{
    border-color: var(--sw-accent) !important;
    box-shadow: 0 0 0 3px {_accent_rgba(p)}, 0.2) !important;
  }}

  .top-site-outer .title {{
    color: var(--sw-text) !important;
  }}

  .top-site-outer .tile {{
    background-color: var(--sw-bg-surface) !important;
    border: 1px solid var(--sw-border) !important;
    border-radius: 12px !important;
  }}

  .top-site-outer:hover .tile {{
    background-color: var(--sw-bg-elevated) !important;
    border-color: {_accent_rgba(p)}, 0.3) !important;
  }}

  .card-outer {{
    background-color: var(--sw-bg-surface) !important;
    border: 1px solid var(--sw-border) !important;
    border-radius: 12px !important;
  }}

  .card-outer:hover {{
    border-color: {_accent_rgba(p)}, 0.3) !important;
  }}

  .section-title span {{
    color: var(--sw-text) !important;
  }}
}}

@-moz-document url-prefix("about:") {{
  :root {{
    --in-content-page-background: var(--sw-bg-deepest) !important;
    --in-content-page-color: var(--sw-text) !important;
    --in-content-box-background: var(--sw-bg-surface) !important;
    --in-content-box-border-color: var(--sw-border) !important;
    --in-content-button-background: var(--sw-bg-elevated) !important;
    --in-content-button-background-hover: {p["border"]} !important;
    --in-content-button-background-active: var(--sw-accent) !important;
    --in-content-primary-button-background: var(--sw-accent) !important;
    --in-content-primary-button-background-hover: var(--sw-accent-hover) !important;
    --in-content-primary-button-background-active: {p["accent_soft"]} !important;
    --in-content-primary-button-text-color: #ffffff !important;
    --in-content-focus-outline-color: var(--sw-accent) !important;
    --in-content-accent-color: var(--sw-accent) !important;
    --in-content-border-color: var(--sw-border) !important;
    --link-color: {p["accent_rose"]} !important;
    --color-accent-primary: var(--sw-accent) !important;
    --color-accent-primary-hover: var(--sw-accent-hover) !important;
    --color-accent-primary-active: {p["accent_soft"]} !important;
  }}

  body {{
    background-color: var(--sw-bg-deepest) !important;
    color: var(--sw-text) !important;
  }}
}}

@-moz-document url("about:preferences") {{
  body {{
    background-color: var(--sw-bg-deepest) !important;
  }}

  .navigation {{
    background-color: var(--sw-bg-surface) !important;
  }}

  .category:hover {{
    background-color: var(--sw-glow) !important;
  }}

  .category[selected] {{
    background-color: var(--sw-accent) !important;
    color: white !important;
  }}
}}

@-moz-document url("about:addons") {{
  :root {{
    --in-content-page-background: var(--sw-bg-deepest) !important;
  }}
}}

@-moz-document url("about:privatebrowsing") {{
  body {{
    background-color: var(--sw-bg-deepest) !important;
    color: var(--sw-text) !important;
  }}
}}

@-moz-document url("about:blank") {{
  body {{
    background-color: var(--sw-bg-deepest) !important;
  }}
}}

* {{
  scrollbar-color: {_accent_rgba(p)}, 0.4) transparent !important;
  scrollbar-width: thin !important;
}}

::selection {{
  background: {_accent_rgba(p)}, 0.4) !important;
  color: var(--sw-text) !important;
}}
"""


def generate_firefox_userjs() -> str:
    return """user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
"""


def generate_chrome_manifest(p: dict, name: str) -> str:
    r_frame, g_frame, b_frame = hex_to_rgb(p["bg_main"])
    r_fi, g_fi, b_fi = hex_to_rgb(p["bg_deepest"])
    r_tb, g_tb, b_tb = hex_to_rgb(p["bg_surface"])
    r_txt, g_txt, b_txt = hex_to_rgb(p["text"])
    r_mut, g_mut, b_mut = hex_to_rgb(p["text_muted"])
    r_brd, g_brd, b_brd = hex_to_rgb(p["border"])
    r_al, g_al, b_al = hex_to_rgb(p["accent_light"])

    # Compute HSL hue for tint (0-1 range)
    from theme_maker.palette import hex_to_hsl

    ah, _, _ = hex_to_hsl(p["accent"])
    hue_tint = ah / 360.0

    data = {
        "manifest_version": 2,
        "version": "1.0",
        "name": name,
        "description": f"Dark theme with accent colors - auto-generated by Theme Maker",
        "theme": {
            "colors": {
                "frame": [r_frame, g_frame, b_frame],
                "frame_inactive": [r_fi, g_fi, b_fi],
                "frame_incognito": [r_frame, g_frame, b_frame],
                "frame_incognito_inactive": [r_fi, g_fi, b_fi],
                "toolbar": [r_tb, g_tb, b_tb],
                "tab_text": [r_txt, g_txt, b_txt],
                "tab_background_text": [r_mut, g_mut, b_mut],
                "bookmark_text": [r_txt, g_txt, b_txt],
                "ntp_background": [r_fi, g_fi, b_fi],
                "ntp_text": [r_txt, g_txt, b_txt],
                "ntp_link": [r_al, g_al, b_al],
                "ntp_header": [r_brd, g_brd, b_brd],
                "button_background": [r_tb, g_tb, b_tb],
                "omnibox_background": [r_fi, g_fi, b_fi],
                "omnibox_text": [r_txt, g_txt, b_txt],
            },
            "tints": {
                "buttons": [hue_tint, 0.7, 0.6],
                "frame": [-1, -1, -1],
                "frame_inactive": [-1, -1, -1],
                "frame_incognito": [hue_tint, 0.8, 0.2],
                "frame_incognito_inactive": [hue_tint, 0.5, 0.1],
                "background_tab": [hue_tint, 0.3, 0.5],
            },
            "properties": {
                "ntp_background_alignment": "center",
                "ntp_background_repeat": "repeat",
                "ntp_logo_alternate": 0,
            },
        },
    }
    return json.dumps(data, indent=2)


def write_browser_files(output_dir: Path, p: dict, name: str):
    """Write all browser theme files."""
    # Firefox
    ff_dir = output_dir / "browsers" / "firefox"
    ff_dir.mkdir(parents=True, exist_ok=True)
    (ff_dir / "userChrome.css").write_text(generate_firefox_userchrome(p, name))
    (ff_dir / "userContent.css").write_text(generate_firefox_usercontent(p, name))
    (ff_dir / "user.js").write_text(generate_firefox_userjs())

    # Zen Browser (same format as Firefox)
    zen_dir = output_dir / "browsers" / "zen"
    zen_dir.mkdir(parents=True, exist_ok=True)
    (zen_dir / "userChrome.css").write_text(generate_firefox_userchrome(p, name))
    (zen_dir / "userContent.css").write_text(generate_firefox_usercontent(p, name))
    (zen_dir / "user.js").write_text(generate_firefox_userjs())

    # Chrome
    chrome_dir = output_dir / "browsers" / "chrome"
    chrome_dir.mkdir(parents=True, exist_ok=True)
    (chrome_dir / "manifest.json").write_text(generate_chrome_manifest(p, name))
