"""Fastfetch config and INSTALL.md generators."""

import json
from pathlib import Path
from theme_maker.palette import get_gnome_accent_name


def generate_fastfetch_config(p: dict, wallpaper: str) -> str:
    data = {
        "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
        "logo": {
            "source": wallpaper,
            "type": "chafa",
            "width": 36,
            "height": 18,
            "preserveAspectRatio": True,
            "padding": {"top": 0, "left": 1, "right": 2},
        },
        "modules": [
            {
                "type": "custom",
                "format": "\033[1;31m╭──────────────────────────────────────╮\033[0m",
            },
            {
                "type": "title",
                "format": "\033[1;31m│  \033[0m\033[1;97m{1}\033[0m\033[31m@\033[0m\033[1;97m{2}\033[0m",
                "key": " ",
            },
            {
                "type": "custom",
                "format": "\033[1;31m╰──────────────────────────────────────╯\033[0m",
            },
            "break",
            {"type": "os", "key": "  OS", "keyColor": "red"},
            {"type": "kernel", "key": "  Kernel", "keyColor": "red"},
            {"type": "uptime", "key": "  Uptime", "keyColor": "red"},
            {"type": "packages", "key": "  Pkgs", "keyColor": "red"},
            {"type": "shell", "key": "  Shell", "keyColor": "red"},
            "break",
            {
                "type": "custom",
                "format": "\033[31m  ── \033[1mDesktop\033[0m\033[31m ───────────────────────────\033[0m",
            },
            {"type": "de", "key": "  DE", "keyColor": "red"},
            {"type": "wm", "key": "  WM", "keyColor": "red"},
            {"type": "display", "key": "  Display", "keyColor": "red"},
            {"type": "terminal", "key": "  Term", "keyColor": "red"},
            {"type": "theme", "key": "  Theme", "keyColor": "red"},
            {"type": "icons", "key": "  Icons", "keyColor": "red"},
            {"type": "cursor", "key": "  Cursor", "keyColor": "red"},
            "break",
            {
                "type": "custom",
                "format": "\033[31m  ── \033[1mHardware\033[0m\033[31m ──────────────────────────\033[0m",
            },
            {"type": "host", "key": "  Host", "keyColor": "red"},
            {"type": "cpu", "key": "  CPU", "keyColor": "red"},
            {"type": "gpu", "key": "  GPU", "keyColor": "red"},
            {"type": "memory", "key": "  Memory", "keyColor": "red"},
            {"type": "disk", "key": "  Disk", "keyColor": "red", "folders": "/"},
            {"type": "battery", "key": "  Battery", "keyColor": "red"},
            "break",
            {"type": "colors", "paddingLeft": 4, "symbol": "circle"},
        ],
    }
    return json.dumps(data, indent=4)


def generate_install_md(name: str, p: dict) -> str:
    slug = name.lower().replace(" ", "-")
    editor_slug = slug.replace("-", "")
    palette_file = f"{slug}.palette"
    accent_name = get_gnome_accent_name(p["accent"])
    mode = p.get("mode", "dark")
    color_scheme = "prefer-dark" if mode == "dark" else "prefer-light"

    return f"""# {name} Theme - Installation Guide

A system-wide {mode} theme with accent color (`{p["accent"]}`) auto-generated by Theme Maker from your wallpaper.
Designed for Fedora + GNOME on Wayland.

To reapply this generated theme later without regenerating it, run:

```bash
theme-maker --apply-existing "$(pwd)"
```

## Prerequisites

- Fedora with GNOME desktop (Wayland)
- GNOME Extensions: User Theme, Dash to Dock, Blur My Shell, Just Perfection
- [Starship prompt](https://starship.rs/)
- [pywal](https://github.com/dylanaraps/pywal)
- [Fastfetch](https://github.com/fastfetch-cli/fastfetch) + [chafa](https://hpjansson.org/chafa/)
- [Papirus Icon Theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)
- [Bibata Cursor Theme](https://github.com/ful1e5/Bibata_Cursor)

---

## 1. GTK Theme

```bash
mkdir -p ~/.themes/{name}/{{gtk-3.0,gtk-4.0,gnome-shell}}
cp gtk-theme/gtk3.css ~/.themes/{name}/gtk-3.0/gtk.css
cp gtk-theme/gtk4.css ~/.themes/{name}/gtk-4.0/gtk.css
cp gtk-theme/index.theme ~/.themes/{name}/index.theme
cp gnome-shell/gnome-shell.css ~/.themes/{name}/gnome-shell/gnome-shell.css

mkdir -p ~/.config/gtk-3.0 ~/.config/gtk-4.0
ln -sf ~/.themes/{name}/gtk-3.0/gtk.css ~/.config/gtk-3.0/gtk.css
ln -sf ~/.themes/{name}/gtk-4.0/gtk.css ~/.config/gtk-4.0/gtk.css
cp gtk-config/gtk3-settings.ini ~/.config/gtk-3.0/settings.ini
cp gtk-config/gtk4-settings.ini ~/.config/gtk-4.0/settings.ini
```

## 2. GNOME Settings

```bash
gsettings set org.gnome.desktop.interface gtk-theme '{name}'
gsettings set org.gnome.desktop.interface color-scheme '{color_scheme}'
gsettings set org.gnome.desktop.interface accent-color '{accent_name}'
gsettings set org.gnome.shell.extensions.user-theme name '{name}'
```

## 3. Dash to Dock

```bash
gsettings set org.gnome.shell.extensions.dash-to-dock custom-background-color true
gsettings set org.gnome.shell.extensions.dash-to-dock background-color '{p["bg_deepest"]}'
gsettings set org.gnome.shell.extensions.dash-to-dock background-opacity 0.6
gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode 'FIXED'
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-shrink true
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-customize-running-dots true
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-color '{p["accent"]}'
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-border-color '{p["accent_light"]}'
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-border-width 0
gsettings set org.gnome.shell.extensions.dash-to-dock running-indicator-style 'DOTS'
```

## 4. Terminal (Ptyxis)

```bash
mkdir -p ~/.local/share/org.gnome.Ptyxis/palettes
cp terminal/ptyxis/{palette_file} ~/.local/share/org.gnome.Ptyxis/palettes/
```

Then select **{name}** in Ptyxis preferences.

## 5. Starship Prompt

```bash
cp terminal/starship/starship.toml ~/.config/starship.toml
```

Add to `~/.bashrc`: `eval "$(starship init bash)"`

## 6. Pywal Colors

```bash
mkdir -p ~/.cache/wal
cp terminal/pywal/* ~/.cache/wal/
```

Add to `~/.bashrc`:
```bash
cat ~/.cache/wal/sequences
source ~/.cache/wal/colors.sh
```

## 7. Xresources

```bash
cp terminal/Xresources ~/.Xresources
xrdb -merge ~/.Xresources
```

## 8. Firefox

```bash
FIREFOX_PROFILE=$(find ~/.mozilla/firefox -maxdepth 1 -name "*.default-release" | head -1)
mkdir -p "$FIREFOX_PROFILE/chrome"
cp browsers/firefox/userChrome.css "$FIREFOX_PROFILE/chrome/"
cp browsers/firefox/userContent.css "$FIREFOX_PROFILE/chrome/"
printf '\nuser_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);\n' >> "$FIREFOX_PROFILE/user.js"
```

## 9. Zen Browser (Flatpak)

```bash
ZEN_PROFILE=$(find ~/.var/app/app.zen_browser.zen/.zen -maxdepth 1 -name "*.Default*" | head -1)
mkdir -p "$ZEN_PROFILE/chrome"
cp browsers/zen/userChrome.css "$ZEN_PROFILE/chrome/"
cp browsers/zen/userContent.css "$ZEN_PROFILE/chrome/"
printf '\nuser_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);\n' >> "$ZEN_PROFILE/user.js"
```

## 10. Chrome, Chromium, Brave, Helium, and Edge

```bash
mkdir -p ~/.local/share/theme-maker/browser-theme
cp -r browsers/chrome/* ~/.local/share/theme-maker/browser-theme/
```

Load `~/.local/share/theme-maker/browser-theme` once via `chrome://extensions` >
Developer mode > Load unpacked. Future `theme-maker --apply` runs refresh this stable
folder and any older active Theme Maker theme locations; restart the browser to reload it.
`--apply` detects Helium's `~/.config/net.imput.helium` profiles and both native
and Flatpak Brave profiles. For Brave Flatpak it resolves document-portal theme
paths to their original host folders and also stages a stable copy under
`~/.var/app/com.brave.Browser/config/theme-maker/browser-theme`.

## 11. VS Code (Flatpak)

```bash
VSCODE_EXT=~/.var/app/com.visualstudio.code/data/vscode/extensions
mkdir -p "$VSCODE_EXT/{slug}-theme/themes"
cp editors/vscode/package.json "$VSCODE_EXT/{slug}-theme/"
cp editors/vscode/themes/* "$VSCODE_EXT/{slug}-theme/themes/"
```

Then set `"workbench.colorTheme": "{name}"` in settings, or use `Ctrl+K Ctrl+T`.

## 12. Antigravity

Use `theme-maker --apply`. It copies the extension into
`~/.antigravity/extensions/`, registers it in Antigravity's extension registry,
and updates `~/.config/Antigravity/User/settings.json` without calling the
hanging command-line extension installer. Restart Antigravity afterward.

## 13. OpenCode

```bash
mkdir -p ~/.config/opencode/themes
cp editors/opencode/{editor_slug}.json ~/.config/opencode/themes/
```

Set `"theme": "{editor_slug}"` in `~/.config/opencode/tui.json`.

## 14. Kilo Code

```bash
mkdir -p ~/.config/kilo/themes
cp editors/kilo/{editor_slug}.json ~/.config/kilo/themes/
```

Set `"theme": "{editor_slug}"` in `~/.config/kilo/kilo.jsonc`.

## 15. Codex CLI

```bash
mkdir -p ~/.codex/themes
cp editors/codex/{slug}.tmTheme ~/.codex/themes/
```

Then set this in `~/.codex/config.toml`:

```toml
[tui]
theme = "{slug}"
```

## 16. Fastfetch

```bash
mkdir -p ~/.config/fastfetch
cp fastfetch/config.jsonc ~/.config/fastfetch/config.jsonc
```

## 17. Icon Theme

```bash
mkdir -p ~/.icons/{slug}
cp -r icons/{slug}/* ~/.icons/{slug}/
gsettings set org.gnome.desktop.interface icon-theme '{slug}'
```

## 18. Cursor Theme

```bash
mkdir -p ~/.icons/{slug}-cursors
cp -r cursors/{slug}-cursors/* ~/.icons/{slug}-cursors/
gsettings set org.gnome.desktop.interface cursor-theme '{slug}-cursors'
```

## Color Palette

| Role | Hex |
|------|-----|
| Deepest BG | `{p["bg_deepest"]}` |
| Main BG | `{p["bg_main"]}` |
| Surface | `{p["bg_surface"]}` |
| Elevated | `{p["bg_elevated"]}` |
| Border | `{p["border"]}` |
| **Accent** | **`{p["accent"]}`** |
| Accent Hover | `{p["accent_hover"]}` |
| Accent Light | `{p["accent_light"]}` |
| Accent Soft | `{p["accent_soft"]}` |
| Rose | `{p["accent_rose"]}` |
| Text | `{p["text"]}` |
| Text Muted | `{p["text_muted"]}` |
| Green | `{p["green"]}` |
| Blue | `{p["blue"]}` |
| Magenta | `{p["magenta"]}` |
| Cyan | `{p["cyan"]}` |

---

*Auto-generated by Theme Maker for GNOME.*
"""


def write_extra_files(output_dir: Path, p: dict, name: str, wallpaper: str):
    """Write fastfetch config and INSTALL.md."""
    # Fastfetch
    ff_dir = output_dir / "fastfetch"
    ff_dir.mkdir(parents=True, exist_ok=True)
    (ff_dir / "config.jsonc").write_text(generate_fastfetch_config(p, wallpaper))

    # INSTALL.md
    (output_dir / "INSTALL.md").write_text(generate_install_md(name, p))
