"""GTK3, GTK4/libadwaita, and GNOME Shell CSS generators."""

from pathlib import Path


def generate_gtk3_css(p: dict, name: str) -> str:
    return f"""/* {name} GTK3 Theme - Auto-generated by Theme Maker */

/* ===== Color Definitions ===== */
@define-color theme_bg_color {p["bg_main"]};
@define-color theme_fg_color {p["text"]};
@define-color theme_base_color {p["bg_deepest"]};
@define-color theme_text_color {p["text"]};
@define-color theme_selected_bg_color {p["accent"]};
@define-color theme_selected_fg_color #ffffff;
@define-color theme_tooltip_bg_color {p["bg_surface"]};
@define-color theme_tooltip_fg_color {p["text"]};
@define-color insensitive_bg_color {p["insensitive_bg"]};
@define-color insensitive_fg_color {p["text_dim"]};
@define-color borders {p["border"]};
@define-color unfocused_borders {p["bg_elevated"]};
@define-color warning_color {p["warning"]};
@define-color error_color {p["accent_light"]};
@define-color success_color {p["green"]};
@define-color destructive_color {p["accent_light"]};
@define-color link_color {p["accent_rose"]};
@define-color content_view_bg {p["bg_deepest"]};

/* ===== Global ===== */
* {{
  outline-color: alpha(@theme_selected_bg_color, 0.5);
  -gtk-secondary-caret-color: @theme_selected_bg_color;
}}

/* ===== Window ===== */
window, .background {{
  background-color: @theme_bg_color;
  color: @theme_fg_color;
}}

decoration {{
  border-radius: 12px;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.6),
              0 0 0 1px alpha(@theme_selected_bg_color, 0.1);
  margin: 6px;
}}

/* ===== Header Bar ===== */
headerbar, .titlebar {{
  background: linear-gradient(to bottom, {p["bg_surface"]}, {p["bg_main"]});
  border-bottom: 1px solid {p["border"]};
  color: @theme_fg_color;
  padding: 4px 8px;
  min-height: 42px;
  border-radius: 12px 12px 0 0;
}}

headerbar:backdrop {{
  background: {p["bg_main"]};
  border-bottom-color: {p["bg_elevated"]};
  color: {p["text_muted"]};
}}

headerbar .title, headerbar .subtitle {{
  color: @theme_fg_color;
}}

headerbar .subtitle {{
  color: {p["text_muted"]};
}}

/* ===== Buttons ===== */
button {{
  background: linear-gradient(to bottom, {p["bg_elevated"]}, {p["bg_surface"]});
  border: 1px solid {p["border"]};
  border-radius: 8px;
  color: @theme_fg_color;
  padding: 6px 16px;
  min-height: 24px;
  transition: all 200ms ease;
}}

button:hover {{
  background: linear-gradient(to bottom, {p["border"]}, {p["bg_elevated"]});
  border-color: {p["border_bright"]};
}}

button:active, button:checked {{
  background: linear-gradient(to bottom, {p["accent"]}, {p["accent_soft"]});
  border-color: {p["accent_light"]};
  color: white;
}}

button:disabled {{
  background: {p["insensitive_bg"]};
  color: {p["text_dim"]};
  border-color: {p["bg_elevated"]};
}}

button.suggested-action {{
  background: linear-gradient(to bottom, {p["accent"]}, {p["accent_soft"]});
  border-color: {p["accent_hover"]};
  color: white;
}}

button.suggested-action:hover {{
  background: linear-gradient(to bottom, {p["accent_hover"]}, {p["accent"]});
}}

button.destructive-action {{
  background: linear-gradient(to bottom, {p["accent"]}, {p["accent_soft"]});
  border-color: {p["accent_light"]};
  color: white;
}}

button.flat {{
  background: transparent;
  border: 1px solid transparent;
}}

button.flat:hover {{
  background: alpha(@theme_selected_bg_color, 0.15);
  border-color: transparent;
}}

/* ===== Entries / Text Inputs ===== */
entry {{
  background: {p["bg_deepest"]};
  border: 1px solid {p["border"]};
  border-radius: 8px;
  color: @theme_fg_color;
  padding: 6px 10px;
  min-height: 24px;
  caret-color: @theme_selected_bg_color;
}}

entry:focus {{
  border-color: @theme_selected_bg_color;
  box-shadow: 0 0 0 2px alpha(@theme_selected_bg_color, 0.25);
}}

entry:disabled {{
  background: {p["insensitive_bg"]};
  color: {p["text_dim"]};
}}

/* ===== Selections ===== */
selection, *:selected {{
  background-color: @theme_selected_bg_color;
  color: @theme_selected_fg_color;
}}

/* ===== Lists & Rows ===== */
list, listview {{
  background-color: @theme_bg_color;
  color: @theme_fg_color;
}}

row {{
  border-radius: 8px;
  padding: 4px;
}}

row:hover {{
  background-color: alpha(@theme_selected_bg_color, 0.1);
}}

row:selected, row:active {{
  background-color: alpha(@theme_selected_bg_color, 0.2);
}}

/* ===== Sidebar ===== */
.sidebar, placessidebar {{
  background-color: {p["bg_deepest"]};
  border-right: 1px solid {p["bg_elevated"]};
}}

.sidebar row:hover, placessidebar row:hover {{
  background-color: alpha(@theme_selected_bg_color, 0.1);
}}

.sidebar row:selected, placessidebar row:selected {{
  background-color: alpha(@theme_selected_bg_color, 0.2);
  color: @theme_fg_color;
}}

/* ===== Scrollbar ===== */
scrollbar slider {{
  background-color: alpha(@theme_selected_bg_color, 0.4);
  border-radius: 100px;
  min-width: 6px;
  min-height: 6px;
}}

scrollbar slider:hover {{
  background-color: alpha(@theme_selected_bg_color, 0.6);
}}

scrollbar slider:active {{
  background-color: @theme_selected_bg_color;
}}

scrollbar trough {{
  background-color: transparent;
}}

/* ===== Switch ===== */
switch {{
  background: {p["bg_elevated"]};
  border: 1px solid {p["border"]};
  border-radius: 100px;
  min-width: 48px;
  min-height: 24px;
}}

switch:checked {{
  background: @theme_selected_bg_color;
  border-color: {p["accent_hover"]};
}}

switch slider {{
  background: {p["text"]};
  border-radius: 100px;
  min-width: 20px;
  min-height: 20px;
}}

/* ===== Check & Radio ===== */
check, radio {{
  background: {p["bg_deepest"]};
  border: 2px solid {p["border"]};
  min-width: 18px;
  min-height: 18px;
}}

check {{
  border-radius: 4px;
}}

radio {{
  border-radius: 100%;
}}

check:checked, radio:checked {{
  background: @theme_selected_bg_color;
  border-color: @theme_selected_bg_color;
  color: white;
}}

/* ===== Scale (Slider) ===== */
scale trough {{
  background: {p["bg_elevated"]};
  border-radius: 100px;
  min-height: 6px;
}}

scale highlight {{
  background: @theme_selected_bg_color;
  border-radius: 100px;
}}

scale slider {{
  background: {p["text"]};
  border: 2px solid @theme_selected_bg_color;
  border-radius: 100%;
  min-width: 18px;
  min-height: 18px;
}}

/* ===== Progress Bar ===== */
progressbar trough {{
  background: {p["bg_elevated"]};
  border-radius: 100px;
}}

progressbar progress {{
  background: linear-gradient(to right, {p["accent"]}, {p["accent_light"]});
  border-radius: 100px;
}}

/* ===== Tooltip ===== */
tooltip, tooltip.background {{
  background-color: {p["bg_surface"]};
  border: 1px solid {p["border"]};
  border-radius: 8px;
  color: @theme_fg_color;
}}

/* ===== Menu & Popover ===== */
menu, .menu, popover, popover.background {{
  background-color: {p["bg_surface"]};
  border: 1px solid {p["border"]};
  border-radius: 12px;
  color: @theme_fg_color;
  padding: 4px;
}}

menuitem, modelbutton {{
  border-radius: 8px;
  padding: 6px 10px;
}}

menuitem:hover, modelbutton:hover {{
  background-color: alpha(@theme_selected_bg_color, 0.2);
}}

/* ===== Notebook (Tabs) ===== */
notebook {{
  background: @theme_bg_color;
}}

notebook header {{
  background: {p["bg_deepest"]};
  border-color: {p["bg_elevated"]};
}}

notebook tab {{
  background: transparent;
  border-radius: 8px 8px 0 0;
  padding: 6px 16px;
  color: {p["text_muted"]};
}}

notebook tab:checked {{
  background: @theme_bg_color;
  color: @theme_fg_color;
  border-bottom: 2px solid @theme_selected_bg_color;
}}

/* ===== Info/Action Bars ===== */
.info, infobar {{
  background-color: alpha(@theme_selected_bg_color, 0.15);
  border: 1px solid alpha(@theme_selected_bg_color, 0.3);
  border-radius: 8px;
}}

/* ===== Dialogs ===== */
messagedialog .dialog-vbox {{
  background: {p["bg_surface"]};
}}

messagedialog .titlebar {{
  background: {p["bg_surface"]};
}}

/* ===== View / Treeview ===== */
.view, textview, treeview {{
  background-color: {p["bg_deepest"]};
  color: @theme_fg_color;
}}

treeview:hover {{
  background-color: alpha(@theme_selected_bg_color, 0.1);
}}

treeview:selected {{
  background-color: alpha(@theme_selected_bg_color, 0.25);
}}

/* ===== Pathbar / Breadcrumbs ===== */
.path-bar button {{
  border-radius: 6px;
}}

.path-bar button:checked {{
  background: alpha(@theme_selected_bg_color, 0.2);
}}

/* ===== OSD ===== */
.osd {{
  background-color: alpha({p["bg_deepest"]}, 0.9);
  border: 1px solid {p["border"]};
  border-radius: 12px;
  color: @theme_fg_color;
}}

/* ===== Linked Buttons ===== */
.linked > button {{
  border-radius: 0;
}}

.linked > button:first-child {{
  border-radius: 8px 0 0 8px;
}}

.linked > button:last-child {{
  border-radius: 0 8px 8px 0;
}}

.linked > button:only-child {{
  border-radius: 8px;
}}

/* ===== Nautilus / Files ===== */
.nautilus-window .sidebar {{
  background-color: {p["bg_deepest"]};
}}

.nautilus-window .floating-bar {{
  background-color: alpha(@theme_selected_bg_color, 0.9);
  border-radius: 8px;
  color: white;
}}

/* ===== Calendar ===== */
calendar {{
  background: {p["bg_surface"]};
  border: 1px solid {p["border"]};
  border-radius: 8px;
  color: @theme_fg_color;
}}

calendar:selected {{
  background: @theme_selected_bg_color;
  color: white;
}}

/* ===== Separator ===== */
separator {{
  background-color: {p["bg_elevated"]};
  min-height: 1px;
  min-width: 1px;
}}

/* ===== Revealer Animations ===== */
revealer > * {{
  transition: all 200ms ease;
}}

/* ===== AdwWindow / libadwaita overrides ===== */
.navigation-sidebar row:selected {{
  background-color: alpha(@theme_selected_bg_color, 0.2);
}}

.card {{
  background-color: {p["bg_surface"]};
  border: 1px solid {p["bg_elevated"]};
  border-radius: 12px;
}}

preferencesgroup {{
  background-color: {p["bg_surface"]};
  border-radius: 12px;
}}

/* ===== Stack Sidebar ===== */
stacksidebar list {{
  background-color: {p["bg_deepest"]};
}}

stacksidebar row:selected {{
  background-color: alpha(@theme_selected_bg_color, 0.2);
}}

/* ===== Focus ===== */
*:focus {{
  outline: 2px solid alpha(@theme_selected_bg_color, 0.5);
  outline-offset: -2px;
}}

/* ===== Dim Label ===== */
.dim-label, label.dim-label {{
  color: {p["text_muted"]};
}}

/* ===== Level Bar ===== */
levelbar block.filled {{
  background-color: @theme_selected_bg_color;
  border-radius: 4px;
}}

levelbar block.empty {{
  background-color: {p["bg_elevated"]};
  border-radius: 4px;
}}

/* ===== Spinner ===== */
spinner {{
  color: @theme_selected_bg_color;
}}

/* ===== Window Decoration - Remove colored active border ===== */
window.background {{
  border: none;
  outline: none;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.5);
}}

window.background:backdrop {{
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
}}

window,
window.solid-csd,
window.csd {{
  border: none;
  outline: none;
}}

window.background decoration {{
  border: none;
  outline: none;
}}

window.background decoration:backdrop {{
  border: none;
}}

headerbar {{
  border-top: none;
}}

window.background:focus-within {{
  outline: none;
  border: none;
}}
"""


def generate_gtk4_css(p: dict, name: str) -> str:
    return f"""/* {name} GTK4/libadwaita Theme - Auto-generated by Theme Maker */

/* ===== Named Colors (libadwaita) ===== */
@define-color accent_color {p["accent"]};
@define-color accent_bg_color {p["accent"]};
@define-color accent_fg_color #ffffff;
@define-color destructive_color {p["accent_light"]};
@define-color destructive_bg_color {p["accent_light"]};
@define-color destructive_fg_color #ffffff;
@define-color success_color {p["green"]};
@define-color success_bg_color {p["green"]};
@define-color success_fg_color #ffffff;
@define-color warning_color {p["warning"]};
@define-color warning_bg_color {p["warning"]};
@define-color warning_fg_color rgba(0,0,0,0.8);
@define-color error_color {p["accent_light"]};
@define-color error_bg_color {p["accent_light"]};
@define-color error_fg_color #ffffff;

@define-color window_bg_color {p["bg_main"]};
@define-color window_fg_color {p["text"]};
@define-color view_bg_color {p["bg_deepest"]};
@define-color view_fg_color {p["text"]};
@define-color headerbar_bg_color {p["bg_surface"]};
@define-color headerbar_fg_color {p["text"]};
@define-color headerbar_border_color {p["border"]};
@define-color headerbar_backdrop_color {p["bg_main"]};
@define-color headerbar_shade_color rgba(0,0,0,0.4);
@define-color card_bg_color {p["bg_surface"]};
@define-color card_fg_color {p["text"]};
@define-color card_shade_color rgba(0,0,0,0.3);
@define-color dialog_bg_color {p["bg_surface"]};
@define-color dialog_fg_color {p["text"]};
@define-color popover_bg_color {p["bg_surface"]};
@define-color popover_fg_color {p["text"]};
@define-color shade_color rgba(0,0,0,0.5);
@define-color scrollbar_outline_color rgba(0,0,0,0.3);
@define-color sidebar_bg_color {p["bg_deepest"]};
@define-color sidebar_fg_color {p["text"]};
@define-color sidebar_backdrop_color {p["bg_deepest"]};
@define-color sidebar_shade_color rgba(0,0,0,0.4);
@define-color thumbnail_bg_color {p["bg_surface"]};
@define-color thumbnail_fg_color {p["text"]};

/* ===== Window ===== */
window.background {{
  background-color: @window_bg_color;
  color: @window_fg_color;
}}

/* ===== Header Bar ===== */
headerbar {{
  background: linear-gradient(to bottom, {p["bg_surface"]}, {p["bg_main"]});
  border-bottom: 1px solid {p["border"]};
  color: @headerbar_fg_color;
}}

headerbar:backdrop {{
  background-color: @headerbar_backdrop_color;
  border-bottom-color: {p["bg_elevated"]};
}}

/* ===== Buttons ===== */
button {{
  background: linear-gradient(to bottom, {p["bg_elevated"]}, {p["bg_surface"]});
  border: 1px solid {p["border"]};
  border-radius: 8px;
  color: @window_fg_color;
  transition: all 200ms ease;
}}

button:hover {{
  background: linear-gradient(to bottom, {p["border"]}, {p["bg_elevated"]});
  border-color: {p["border_bright"]};
}}

button:active, button:checked {{
  background: linear-gradient(to bottom, @accent_bg_color, {p["accent_soft"]});
  border-color: {p["accent_light"]};
  color: white;
}}

button.flat {{
  background: transparent;
  border-color: transparent;
}}

button.flat:hover {{
  background: alpha(@accent_color, 0.15);
}}

button.suggested-action {{
  background: linear-gradient(to bottom, @accent_bg_color, {p["accent_soft"]});
  color: white;
  border-color: {p["accent_hover"]};
}}

button.destructive-action {{
  background: linear-gradient(to bottom, @destructive_bg_color, {p["accent_soft"]});
  color: white;
}}

/* ===== Entry ===== */
entry {{
  background: @view_bg_color;
  border: 1px solid {p["border"]};
  border-radius: 8px;
  color: @view_fg_color;
  caret-color: @accent_color;
}}

entry:focus-within {{
  border-color: @accent_color;
  box-shadow: 0 0 0 2px alpha(@accent_color, 0.25);
}}

/* ===== Selection ===== */
selection {{
  background-color: @accent_bg_color;
  color: @accent_fg_color;
}}

/* ===== Lists ===== */
list, listview {{
  background-color: @window_bg_color;
}}

row {{
  border-radius: 8px;
}}

row:hover {{
  background-color: alpha(@accent_color, 0.08);
}}

row:selected {{
  background-color: alpha(@accent_color, 0.15);
}}

row:active {{
  background-color: alpha(@accent_color, 0.2);
}}

/* ===== Navigation / Sidebar ===== */
.navigation-sidebar {{
  background-color: @sidebar_bg_color;
}}

.navigation-sidebar row:selected {{
  background-color: alpha(@accent_color, 0.15);
}}

/* ===== Cards ===== */
.card {{
  background-color: @card_bg_color;
  border: 1px solid {p["bg_elevated"]};
  border-radius: 12px;
  color: @card_fg_color;
}}

/* ===== Popover ===== */
popover, popover.background {{
  background-color: @popover_bg_color;
  border: 1px solid {p["border"]};
  border-radius: 12px;
  color: @popover_fg_color;
}}

popover modelbutton:hover {{
  background-color: alpha(@accent_color, 0.15);
  border-radius: 8px;
}}

/* ===== Switch ===== */
switch {{
  background: {p["bg_elevated"]};
  border-radius: 100px;
}}

switch:checked {{
  background: @accent_bg_color;
}}

/* ===== Check/Radio ===== */
check:checked, radio:checked {{
  background: @accent_bg_color;
  color: white;
}}

/* ===== Scale ===== */
scale trough {{
  background: {p["bg_elevated"]};
  border-radius: 100px;
}}

scale highlight {{
  background: @accent_bg_color;
  border-radius: 100px;
}}

scale slider {{
  background: {p["text"]};
  border: 2px solid @accent_color;
  border-radius: 100%;
}}

/* ===== Progress ===== */
progressbar trough {{
  background: {p["bg_elevated"]};
  border-radius: 100px;
}}

progressbar progress {{
  background: linear-gradient(to right, @accent_color, {p["accent_light"]});
  border-radius: 100px;
}}

/* ===== Scrollbar ===== */
scrollbar slider {{
  background-color: alpha(@accent_color, 0.4);
  border-radius: 100px;
}}

scrollbar slider:hover {{
  background-color: alpha(@accent_color, 0.6);
}}

scrollbar slider:active {{
  background-color: @accent_color;
}}

/* ===== Notebook ===== */
notebook tab:checked {{
  border-bottom: 2px solid @accent_color;
  color: @window_fg_color;
}}

notebook tab {{
  color: {p["text_muted"]};
}}

/* ===== Tooltip ===== */
tooltip, tooltip.background {{
  background-color: @popover_bg_color;
  border: 1px solid {p["border"]};
  border-radius: 8px;
}}

/* ===== OSD ===== */
.osd {{
  background-color: alpha({p["bg_deepest"]}, 0.9);
  border: 1px solid {p["border"]};
  border-radius: 12px;
}}

/* ===== Separator ===== */
separator {{
  background-color: {p["bg_elevated"]};
}}

/* ===== Dim Label ===== */
.dim-label {{
  color: {p["text_muted"]};
}}

/* ===== AdwTabBar ===== */
tabbar tab:checked {{
  background: alpha(@accent_color, 0.15);
  border-bottom: 2px solid @accent_color;
}}

tabbar tab:hover {{
  background: alpha(@accent_color, 0.08);
}}

/* ===== AdwBanner ===== */
banner {{
  background-color: alpha(@accent_color, 0.15);
}}

/* ===== Status Page ===== */
statuspage {{
  background-color: @window_bg_color;
}}

/* ===== Preference Groups ===== */
preferencesgroup {{
  background-color: @card_bg_color;
  border-radius: 12px;
}}

/* ===== Spinner ===== */
spinner {{
  color: @accent_color;
}}

/* ===== AdwViewSwitcher ===== */
viewswitcher button:checked {{
  background: alpha(@accent_color, 0.15);
}}

/* ===== Linked Buttons ===== */
.linked > button {{
  border-radius: 0;
}}

.linked > button:first-child {{
  border-radius: 8px 0 0 8px;
}}

.linked > button:last-child {{
  border-radius: 0 8px 8px 0;
}}

.linked > button:only-child {{
  border-radius: 8px;
}}

/* ===== Focus Ring ===== */
*:focus-visible {{
  outline: 2px solid alpha(@accent_color, 0.5);
  outline-offset: -2px;
}}

/* ===== Window Decoration - Remove colored active border ===== */
window.background {{
  border: none;
  outline: none;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.5);
}}

window.background:backdrop {{
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
}}

window,
window.solid-csd,
window.csd {{
  border: none;
  outline: none;
}}

window.background decoration {{
  border: none;
  outline: none;
}}

window.background decoration:backdrop {{
  border: none;
}}

headerbar {{
  border-top: none;
}}

window.background:focus-within {{
  outline: none;
  border: none;
}}
"""


def generate_gnome_shell_css(p: dict, name: str) -> str:
    r, g, b = __import__("theme_maker.palette", fromlist=["hex_to_rgb"]).hex_to_rgb(
        p["accent"]
    )
    accent_rgba = f"rgba({r}, {g}, {b}"

    return f"""/* {name} GNOME Shell Theme - Auto-generated by Theme Maker */

/* ===== Stage / Desktop ===== */
stage {{
  color: {p["text"]};
  font-family: "Inter", "Cantarell", sans-serif;
}}

/* ===== Top Panel ===== */
#panel {{
  background-color: transparent;
  color: {p["text"]};
  font-weight: 500;
  height: 32px;
}}

#panel:overview,
#panel.unlock-screen,
#panel.login-screen {{
  background-color: rgba(13, 13, 13, 0.6);
}}

#panel .panel-button {{
  color: {p["text"]};
  -natural-hpadding: 10px;
  -minimum-hpadding: 6px;
  transition-duration: 200ms;
  border-radius: 8px;
}}

#panel .panel-button:hover {{
  background-color: {accent_rgba}, 0.2);
  color: #ffffff;
}}

#panel .panel-button:active,
#panel .panel-button:checked,
#panel .panel-button:focus {{
  background-color: {accent_rgba}, 0.35);
  color: #ffffff;
}}

/* ===== System Status Indicators ===== */
.panel-status-indicators-box,
.panel-status-menu-box {{
  spacing: 4px;
}}

/* ===== Overview ===== */
#overview {{
  spacing: 24px;
}}

.workspace-thumbnails {{
  spacing: 8px;
}}

/* ===== Dash ===== */
#dash {{
  background-color: alpha({p["bg_deepest"]}, 0.7);
  border: 1px solid alpha({p["border"]}, 0.5);
  border-radius: 16px;
  padding: 4px;
}}

#dash .dash-background {{
  background-color: alpha({p["bg_deepest"]}, 0.7);
  border-radius: 16px;
}}

.dash-item-container .app-well-app .overview-icon {{
  border-radius: 12px;
}}

.dash-item-container .app-well-app:hover .overview-icon {{
  background-color: {accent_rgba}, 0.15);
}}

.dash-item-container .app-well-app:active .overview-icon {{
  background-color: {accent_rgba}, 0.3);
}}

/* ===== App Grid ===== */
.icon-grid {{
  spacing: 8px;
}}

.app-well-app .overview-icon {{
  border-radius: 16px;
  padding: 8px;
}}

.app-well-app:hover .overview-icon {{
  background-color: {accent_rgba}, 0.15);
}}

.app-well-app:active .overview-icon {{
  background-color: {accent_rgba}, 0.3);
}}

/* ===== Search ===== */
#searchEntry {{
  background-color: alpha({p["bg_surface"]}, 0.8);
  border: 1px solid {p["border"]};
  border-radius: 24px;
  color: {p["text"]};
  padding: 8px 16px;
  caret-color: {p["accent"]};
  selection-background-color: {accent_rgba}, 0.5);
}}

#searchEntry:hover {{
  border-color: {accent_rgba}, 0.5);
}}

#searchEntry:focus {{
  border-color: {p["accent"]};
  box-shadow: 0 0 0 2px {accent_rgba}, 0.25);
}}

.search-provider-icon {{
  background-color: alpha({p["bg_surface"]}, 0.6);
  border-radius: 12px;
  padding: 8px;
}}

.search-provider-icon:hover {{
  background-color: {accent_rgba}, 0.15);
}}

.search-provider-icon:focus, .search-provider-icon:selected {{
  background-color: {accent_rgba}, 0.25);
}}

/* ===== Notifications & Calendar ===== */
.message-list-sections {{
  spacing: 8px;
}}

.message {{
  background-color: alpha({p["bg_surface"]}, 0.9);
  border: 1px solid {p["bg_elevated"]};
  border-radius: 12px;
  color: {p["text"]};
  padding: 8px;
}}

.message:hover {{
  background-color: alpha({p["bg_elevated"]}, 0.9);
}}

.message .message-title {{
  color: {p["text"]};
  font-weight: bold;
}}

.message .message-body {{
  color: {p["text_muted"]};
}}

/* ===== Calendar ===== */
.calendar {{
  background-color: alpha({p["bg_surface"]}, 0.95);
  border: 1px solid {p["border"]};
  border-radius: 12px;
  padding: 8px;
}}

.calendar .calendar-month-label {{
  color: {p["text"]};
  font-weight: bold;
}}

.calendar .calendar-day-base {{
  color: {p["text_muted"]};
  border-radius: 100px;
  padding: 4px;
}}

.calendar .calendar-day-base:hover {{
  background-color: {accent_rgba}, 0.15);
}}

.calendar .calendar-day-base:selected {{
  background-color: {p["accent"]};
  color: white;
}}

.calendar .calendar-day-base.calendar-day-heading {{
  color: {p["accent"]};
  font-weight: bold;
}}

.calendar .calendar-today {{
  background-color: {accent_rgba}, 0.3);
  color: white;
  font-weight: bold;
}}

/* ===== Quick Settings / System Menu ===== */
.quick-settings {{
  background-color: alpha({p["bg_deepest"]}, 0.95);
  border: 1px solid {accent_rgba}, 0.15);
  border-radius: 16px;
  padding: 10px;
}}

.quick-settings-grid {{
  spacing: 6px;
}}

.quick-toggle {{
  background-color: alpha({p["bg_surface"]}, 0.8);
  border-radius: 12px;
  border: 1px solid alpha({p["border"]}, 0.5);
  padding: 8px 14px;
  color: {p["text_muted"]};
  font-weight: 400;
}}

.quick-toggle:hover {{
  background-color: alpha({p["bg_elevated"]}, 0.9);
  color: {p["text"]};
}}

.quick-toggle:checked {{
  background-color: {accent_rgba}, 0.18);
  color: {p["accent_rose"]};
  border-color: {accent_rgba}, 0.3);
}}

.quick-toggle:checked:hover {{
  background-color: {accent_rgba}, 0.25);
}}

.quick-toggle .quick-toggle-icon:checked {{
  color: {p["accent"]};
}}

.quick-menu-toggle .quick-toggle {{
  border-radius: 12px 0 0 12px;
}}

.quick-menu-toggle .quick-toggle-arrow {{
  border-radius: 0 12px 12px 0;
  background-color: alpha({p["bg_surface"]}, 0.8);
  border: 1px solid alpha({p["border"]}, 0.5);
  border-left: none;
  color: {p["text_muted"]};
}}

.quick-menu-toggle .quick-toggle-arrow:hover {{
  background-color: alpha({p["bg_elevated"]}, 0.9);
}}

.quick-menu-toggle .quick-toggle-arrow:checked {{
  background-color: {accent_rgba}, 0.15);
  border-color: {accent_rgba}, 0.3);
  color: {p["accent_rose"]};
}}

.quick-slider {{
  padding: 4px 12px;
}}

.quick-slider .slider {{
  color: {p["accent"]};
  -slider-height: 4px;
  -slider-background-color: alpha({p["bg_elevated"]}, 0.8);
  -slider-active-background-color: {p["accent"]};
  -slider-handle-border-color: transparent;
  border-radius: 100px;
}}

.quick-settings .icon-button {{
  background-color: transparent;
  border: none;
  color: {p["text_muted"]};
  border-radius: 8px;
  padding: 6px;
}}

.quick-settings .icon-button:hover {{
  background-color: {accent_rgba}, 0.12);
  color: {p["text"]};
}}

.quick-settings .icon-button:active {{
  background-color: {accent_rgba}, 0.2);
}}

.quick-settings .power-item {{
  color: {p["text_muted"]};
}}

/* ===== Popup Menu ===== */
.popup-menu {{
  color: {p["text"]};
}}

.popup-menu-content {{
  background-color: alpha({p["bg_surface"]}, 0.95);
  border: 1px solid {p["border"]};
  border-radius: 12px;
  padding: 6px;
}}

.popup-menu-item {{
  border-radius: 8px;
  padding: 6px 12px;
  color: {p["text"]};
}}

.popup-menu-item:hover {{
  background-color: {accent_rgba}, 0.15);
}}

.popup-menu-item:active {{
  background-color: {accent_rgba}, 0.3);
  color: white;
}}

.popup-separator-menu-item .popup-sub-menu {{
  background-color: alpha({p["bg_deepest"]}, 0.5);
}}

/* ===== Popup Separator ===== */
.popup-separator-menu-item {{
  background-color: {p["bg_elevated"]};
  height: 1px;
}}

/* ===== Modal Dialog / Prompts ===== */
.modal-dialog {{
  background-color: alpha({p["bg_surface"]}, 0.95);
  border: 1px solid {p["border"]};
  border-radius: 16px;
  color: {p["text"]};
  padding: 24px;
}}

.modal-dialog .modal-dialog-button-box .modal-dialog-button {{
  border-radius: 8px;
  padding: 8px 20px;
}}

/* ===== OSD (Volume/Brightness) ===== */
.osd-window {{
  background-color: alpha({p["bg_deepest"]}, 0.85);
  border: 1px solid {p["border"]};
  border-radius: 16px;
  padding: 16px;
  color: {p["text"]};
}}

.osd-window .level {{
  color: {p["accent"]};
  -slider-height: 6px;
  border-radius: 100px;
}}

/* ===== Workspace Switcher ===== */
.ws-switcher-box {{
  spacing: 8px;
}}

.ws-switcher-active-up, .ws-switcher-active-down {{
  background-color: {p["accent"]};
  border-radius: 8px;
  height: 40px;
}}

.ws-switcher-box .ws-switcher-indicator {{
  background-color: {accent_rgba}, 0.3);
  border-radius: 8px;
}}

/* ===== Window Picker / Workspace Thumb ===== */
.window-caption {{
  background-color: alpha({p["bg_deepest"]}, 0.8);
  border: 1px solid alpha({p["border"]}, 0.5);
  border-radius: 8px;
  color: {p["text"]};
  padding: 4px 12px;
}}

.window-close {{
  background-color: {p["accent"]};
  border-radius: 100%;
  height: 24px;
  width: 24px;
  color: white;
}}

.window-close:hover {{
  background-color: {p["accent_light"]};
}}

/* ===== Screen Shield / Lock ===== */
.screen-shield-background {{
  background-color: {p["bg_deepest"]};
}}

.unlock-dialog {{
  background-color: alpha({p["bg_surface"]}, 0.9);
  border: 1px solid {p["border"]};
  border-radius: 16px;
}}

.unlock-dialog-button {{
  background-color: {p["accent"]};
  border-radius: 100px;
  color: white;
}}

/* ===== Login Dialog ===== */
.login-dialog {{
  background-color: alpha({p["bg_deepest"]}, 0.85);
  border-radius: 16px;
}}

/* ===== Looking Glass (debug) ===== */
#LookingGlassDialog {{
  background-color: alpha({p["bg_deepest"]}, 0.95);
  border: 1px solid {p["border"]};
  border-radius: 12px;
  color: {p["text"]};
}}

/* ===== Switcher Popup (Alt+Tab) ===== */
.switcher-list {{
  background-color: alpha({p["bg_deepest"]}, 0.9);
  border: 1px solid {p["border"]};
  border-radius: 16px;
  padding: 12px;
  color: {p["text"]};
}}

.switcher-list .item-box:selected {{
  background-color: {accent_rgba}, 0.3);
  border-radius: 12px;
}}

/* ===== Tile Preview ===== */
.tile-preview {{
  background-color: {accent_rgba}, 0.15);
  border: 2px solid {accent_rgba}, 0.5);
  border-radius: 12px;
}}

/* ===== Ripple / Click Effect ===== */
.ripple-box {{
  background-color: {accent_rgba}, 0.3);
  border-radius: 100%;
}}

/* ===== World Clock ===== */
.world-clocks-button,
.weather-button {{
  border-radius: 12px;
  padding: 8px 12px;
}}

.world-clocks-button:hover,
.weather-button:hover {{
  background-color: {accent_rgba}, 0.1);
}}
"""


def generate_index_theme(name: str) -> str:
    return f"""[Desktop Entry]
Type=X-GNOME-Metatheme
Name={name}
Comment=Dark theme auto-generated by Theme Maker
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme={name}
MetacityTheme={name}
IconTheme=Papirus-Dark
CursorTheme=Bibata-Modern-Amber
ButtonLayout=appmenu:minimize,maximize,close
"""


def generate_gtk3_settings(name: str) -> str:
    return f"""[Settings]
gtk-theme-name={name}
gtk-icon-theme-name=Papirus-Dark
gtk-cursor-theme-name=Bibata-Modern-Amber
gtk-cursor-theme-size=24
gtk-font-name=Cantarell 11
gtk-application-prefer-dark-theme=true
gtk-decoration-layout=appmenu:minimize,maximize,close
"""


def generate_gtk4_settings() -> str:
    return """[Settings]
gtk-application-prefer-dark-theme=1
"""


def write_gtk_files(output_dir: Path, p: dict, name: str):
    """Write all GTK-related theme files."""
    # GTK theme CSS
    gtk_theme_dir = output_dir / "gtk-theme"
    gtk_theme_dir.mkdir(parents=True, exist_ok=True)
    (gtk_theme_dir / "gtk3.css").write_text(generate_gtk3_css(p, name))
    (gtk_theme_dir / "gtk4.css").write_text(generate_gtk4_css(p, name))
    (gtk_theme_dir / "index.theme").write_text(generate_index_theme(name))

    # GNOME Shell
    shell_dir = output_dir / "gnome-shell"
    shell_dir.mkdir(parents=True, exist_ok=True)
    (shell_dir / "gnome-shell.css").write_text(generate_gnome_shell_css(p, name))

    # GTK config
    config_dir = output_dir / "gtk-config"
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "gtk3-settings.ini").write_text(generate_gtk3_settings(name))
    (config_dir / "gtk4-settings.ini").write_text(generate_gtk4_settings())
