"""Terminal theme generators - Ptyxis, Starship, Pywal, Xresources."""

import json
from pathlib import Path


def generate_ptyxis_palette(p: dict, name: str) -> str:
    return f"""[Palette]
Name={name}
CursorColor={p["accent"]}
CursorTextColor={p["bg_deepest"]}
ForegroundColor={p["text"]}
BackgroundColor={p["bg_deepest"]}
SelectionColor={p["accent"]}
SelectionTextColor=#ffffff
BoldColor={p["text"]}

Color0={p["ansi_black"]}
Color1={p["ansi_red"]}
Color2={p["ansi_green"]}
Color3={p["ansi_yellow"]}
Color4={p["ansi_blue"]}
Color5={p["ansi_magenta"]}
Color6={p["ansi_cyan"]}
Color7={p["ansi_white"]}

Color8={p["ansi_bright_black"]}
Color9={p["ansi_bright_red"]}
Color10={p["ansi_bright_green"]}
Color11={p["ansi_bright_yellow"]}
Color12={p["ansi_bright_blue"]}
Color13={p["ansi_bright_magenta"]}
Color14={p["ansi_bright_cyan"]}
Color15={p["ansi_bright_white"]}
"""


def generate_starship_toml(p: dict) -> str:
    # Map the powerline segments to the wallpaper's HSL palette tints
    c1 = p["accent"]        # Username segment background
    c2 = p["accent_soft"]   # Directory segment background
    c3 = p["accent_rose"]   # Git segment background
    c4 = p["blue"]          # Language/package background
    c5 = p["cyan"]          # Docker segment background
    c6 = p["border"]        # Time segment background
    
    fg_dark = p["bg_deepest"]  # Dark text for light pastel backgrounds
    fg_light = "#ffffff"       # White text for dark/vibrant backgrounds

    return f"""add_newline = false

# Pastel Powerline Preset - Auto-generated with Wallpaper Palette
format = \"\"\"
[░▒▓](fg:{c1})\
$os\
$username\
[](bg:{c2} fg:{c1})\
$directory\
[](fg:{c2} bg:{c3})\
$git_branch\
$git_status\
[](fg:{c3} bg:{c4})\
$rust\
$python\
$nodejs\
$golang\
[](fg:{c4} bg:{c5})\
$docker_context\
[](fg:{c5} bg:{c6})\
$time\
[ ](fg:{c6})\
\"\"\"

[username]
show_always = true
style_user = "bg:{c1} fg:{fg_light} bold"
style_root = "bg:{c1} fg:{fg_light} bold"
format = '[$user]($style)'
disabled = false

[os]
style = "bg:{c1} fg:{fg_light}"
disabled = true

[directory]
style = "bg:{c2} fg:{fg_dark} bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bg:{c3} fg:{fg_dark} bold"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:{c3} fg:{fg_dark} bold"
format = '[$all_status$ahead_behind ]($style)'

[rust]
symbol = "🦀 "
style = "bg:{c4} fg:{fg_dark} bold"
format = '[ $symbol($version) ]($style)'

[python]
symbol = "🐍 "
style = "bg:{c4} fg:{fg_dark} bold"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = "⬢ "
style = "bg:{c4} fg:{fg_dark} bold"
format = '[ $symbol($version) ]($style)'

[golang]
symbol = "🐹 "
style = "bg:{c4} fg:{fg_dark} bold"
format = '[ $symbol($version) ]($style)'

[docker_context]
symbol = "🐳 "
style = "bg:{c5} fg:{fg_dark} bold"
format = '[ $symbol$context ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:{c6} fg:{fg_light} bold"
format = '[ ♥ $time ]($style)'
"""


def generate_pywal_colors_sh(p: dict, wallpaper: str) -> str:
    return f"""# Shell variables
# Auto-generated by Theme Maker
wallpaper="{wallpaper}"

# Special
background='{p["bg_deepest"]}'
foreground='{p["text"]}'
cursor='{p["accent"]}'

# Colors
color0='{p["ansi_black"]}'
color1='{p["ansi_red"]}'
color2='{p["ansi_green"]}'
color3='{p["ansi_yellow"]}'
color4='{p["ansi_blue"]}'
color5='{p["ansi_magenta"]}'
color6='{p["ansi_cyan"]}'
color7='{p["ansi_white"]}'
color8='{p["ansi_bright_black"]}'
color9='{p["ansi_bright_red"]}'
color10='{p["ansi_bright_green"]}'
color11='{p["ansi_bright_yellow"]}'
color12='{p["ansi_bright_blue"]}'
color13='{p["ansi_bright_magenta"]}'
color14='{p["ansi_bright_cyan"]}'
color15='{p["ansi_bright_white"]}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${{LS_COLORS}}:su=30;41:ow=30;42:st=30;44:"
"""


def generate_pywal_colors_json(p: dict, wallpaper: str) -> str:
    data = {
        "wallpaper": wallpaper,
        "alpha": "100",
        "special": {
            "background": p["bg_deepest"],
            "foreground": p["text"],
            "cursor": p["accent"],
        },
        "colors": {
            "color0": p["ansi_black"],
            "color1": p["ansi_red"],
            "color2": p["ansi_green"],
            "color3": p["ansi_yellow"],
            "color4": p["ansi_blue"],
            "color5": p["ansi_magenta"],
            "color6": p["ansi_cyan"],
            "color7": p["ansi_white"],
            "color8": p["ansi_bright_black"],
            "color9": p["ansi_bright_red"],
            "color10": p["ansi_bright_green"],
            "color11": p["ansi_bright_yellow"],
            "color12": p["ansi_bright_blue"],
            "color13": p["ansi_bright_magenta"],
            "color14": p["ansi_bright_cyan"],
            "color15": p["ansi_bright_white"],
        },
    }
    return json.dumps(data, indent=4)


def generate_pywal_colors_css(p: dict, wallpaper: str) -> str:
    return f""":root {{
    --wallpaper: url("{wallpaper}");
    --background: {p["bg_deepest"]};
    --foreground: {p["text"]};
    --cursor: {p["accent"]};
    --color0: {p["ansi_black"]};
    --color1: {p["ansi_red"]};
    --color2: {p["ansi_green"]};
    --color3: {p["ansi_yellow"]};
    --color4: {p["ansi_blue"]};
    --color5: {p["ansi_magenta"]};
    --color6: {p["ansi_cyan"]};
    --color7: {p["ansi_white"]};
    --color8: {p["ansi_bright_black"]};
    --color9: {p["ansi_bright_red"]};
    --color10: {p["ansi_bright_green"]};
    --color11: {p["ansi_bright_yellow"]};
    --color12: {p["ansi_bright_blue"]};
    --color13: {p["ansi_bright_magenta"]};
    --color14: {p["ansi_bright_cyan"]};
    --color15: {p["ansi_bright_white"]};
}}
"""


def generate_pywal_colors_plain(p: dict) -> str:
    keys = [
        "ansi_black",
        "ansi_red",
        "ansi_green",
        "ansi_yellow",
        "ansi_blue",
        "ansi_magenta",
        "ansi_cyan",
        "ansi_white",
        "ansi_bright_black",
        "ansi_bright_red",
        "ansi_bright_green",
        "ansi_bright_yellow",
        "ansi_bright_blue",
        "ansi_bright_magenta",
        "ansi_bright_cyan",
        "ansi_bright_white",
    ]
    return "\n".join(p[k] for k in keys) + "\n"


def generate_pywal_sequences(p: dict) -> str:
    """Generate VTE escape sequences for terminal color injection."""
    keys = [
        "ansi_black",
        "ansi_red",
        "ansi_green",
        "ansi_yellow",
        "ansi_blue",
        "ansi_magenta",
        "ansi_cyan",
        "ansi_white",
        "ansi_bright_black",
        "ansi_bright_red",
        "ansi_bright_green",
        "ansi_bright_yellow",
        "ansi_bright_blue",
        "ansi_bright_magenta",
        "ansi_bright_cyan",
        "ansi_bright_white",
    ]
    seqs = []
    for i, k in enumerate(keys):
        seqs.append(f"\033]4;{i};{p[k]}\033\\")
    # Special: background, foreground, cursor
    seqs.append(f"\033]10;{p['text']}\033\\")
    seqs.append(f"\033]11;{p['bg_deepest']}\033\\")
    seqs.append(f"\033]12;{p['accent']}\033\\")
    seqs.append(f"\033]13;{p['accent']}\033\\")
    seqs.append(f"\033]17;{p['accent']}\033\\")
    seqs.append(f"\033]19;{p['text']}\033\\")
    return "".join(seqs)


def generate_xresources(p: dict) -> str:
    return f"""*.foreground: {p["text"]}
*.background: {p["bg_deepest"]}
*.cursorColor: {p["accent"]}

*.color0: {p["ansi_black"]}
*.color1: {p["ansi_red"]}
*.color2: {p["ansi_green"]}
*.color3: {p["ansi_yellow"]}
*.color4: {p["ansi_blue"]}
*.color5: {p["ansi_magenta"]}
*.color6: {p["ansi_cyan"]}
*.color7: {p["ansi_white"]}
*.color8: {p["ansi_bright_black"]}
*.color9: {p["ansi_bright_red"]}
*.color10: {p["ansi_bright_green"]}
*.color11: {p["ansi_bright_yellow"]}
*.color12: {p["ansi_bright_blue"]}
*.color13: {p["ansi_bright_magenta"]}
*.color14: {p["ansi_bright_cyan"]}
*.color15: {p["ansi_bright_white"]}
"""


def write_terminal_files(output_dir: Path, p: dict, name: str, wallpaper: str):
    """Write all terminal-related theme files."""
    # Ptyxis
    ptyxis_dir = output_dir / "terminal" / "ptyxis"
    ptyxis_dir.mkdir(parents=True, exist_ok=True)
    palette_name = name.lower().replace(" ", "")
    (ptyxis_dir / f"{palette_name}.palette").write_text(
        generate_ptyxis_palette(p, name)
    )

    # Starship
    star_dir = output_dir / "terminal" / "starship"
    star_dir.mkdir(parents=True, exist_ok=True)
    (star_dir / "starship.toml").write_text(generate_starship_toml(p))

    # Pywal
    pywal_dir = output_dir / "terminal" / "pywal"
    pywal_dir.mkdir(parents=True, exist_ok=True)
    (pywal_dir / "colors.sh").write_text(generate_pywal_colors_sh(p, wallpaper))
    (pywal_dir / "colors.json").write_text(generate_pywal_colors_json(p, wallpaper))
    (pywal_dir / "colors.css").write_text(generate_pywal_colors_css(p, wallpaper))
    (pywal_dir / "colors").write_text(generate_pywal_colors_plain(p))
    (pywal_dir / "sequences").write_text(generate_pywal_sequences(p))

    # Xresources
    (output_dir / "terminal" / "Xresources").write_text(generate_xresources(p))
